language: java
jdk: oraclejdk7

notifications:
  email: android.x10f@gmail.com

before_install:
  - repo init -u https://github.com/x10forevers/android-1 -b android-4.4
  - repo sync
  - . build/envsetup.sh
  - brunch omni_yuga-userdebug
