language: java
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6

language: c
compiler:
  - gcc
  - clang
# Change this to your needs
script: ./configure && make

language: cpp
compiler:
  - gcc
  - clang
# Change this to your needs
script: ./configure && make

anguage: python
python:
  - "3.3"
  - "2.7"
  - "2.6"
  
notifications:
  email: android.x10f@gmail.com

before_install:
  - repo init -u https://github.com/x10forevers/android-1 -b android-4.4
  - repo sync
  - . build/envsetup.sh
  - brunch omni_yuga-userdebug
